<?php

namespace app\models;

use GuzzleHttp\Psr7\UploadedFile;
use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $name
 * @property string $content
 * @property int $price
 * @property int $category_id
 * @property int $actve
 * @property int $amount
 * @property int $image
 * @property string $slug
 *
 * @property Category $category
 */
class Product extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description', 'content'], 'string'],
            [['name'], 'required','message'=>'Поле обязательно для заполнения'],
            ['image','string'],
            ['file','file','extensions'=>['jpeg','bmp','csv']],
            [['price', 'category_id', 'actve', 'amount'], 'integer'],
            [['title', 'name', 'slug'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'name' => 'Name',
            'content' => 'Content',
            'price' => 'Price',
            'category_id' => 'Category ID',
            'actve' => 'Actve',
            'amount' => 'Amount',
            'slug' => 'Slug',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

  /*  public function upload(){
        if ($this->validate()){

        }

    }*/

  public function beforeSave($insert)
  {
      $this->file=UploadedFile::getInstance($this,'file');
      $this->upload();

      return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  /*public function getImage($this->image){
      return $this->image;
  }*/
}
